import type {Metadata} from "next";
import {ReactNode} from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = { children: ReactNode}

export default async function MyPageLayout({children}: Props) {
    return (
        <div className="w-[100%] h-[100%]">
                {children}
        </div>
    );
}
