import type { Metadata } from 'next';
import { ReactNode } from 'react';
import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from '@tanstack/react-query';
import { getMe, getMembers } from '@/api/member';
import { getDebts } from '@/api/debts';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

export default async function MyPage({ children }: Props) {
  const queryClient = new QueryClient();
  const token = cookies().get('accessToken')?.value;
  console.log(token);
  await queryClient.prefetchQuery({ queryKey: ['me', token], queryFn: getMe });
  const dehydratedState = dehydrate(queryClient);
  return (
    <div className="h-[100%]">
      <HydrationBoundary state={dehydratedState}>{children}</HydrationBoundary>
    </div>
  );
}
