import type {Metadata} from "next";
import {ReactNode} from "react";
import * as styles from "@/styles/payment/select/payment.css"
import {dehydrate, HydrationBoundary, QueryClient} from "@tanstack/react-query";
import {getMembers} from "@/api/member";
import {getAccount} from "@/api/account";
import {getPayment, getPaymentResult} from "@/api/payment";
import { getReceipt } from '@/api/receipt';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = { children: ReactNode,  params: { payId: string }}

export default async function PaymentModalLayout({children, params}: Props) {
    let {payId} = params;

    const queryClient = new QueryClient();
    await queryClient.prefetchQuery({queryKey: ['payment',Number(payId)], queryFn: getPayment});
    await queryClient.prefetchQuery({queryKey: ['receipt',Number(payId)], queryFn: getReceipt});
    await queryClient.prefetchQuery({queryKey: ['result', Number(payId)], queryFn: getPaymentResult});


    const dehydratedState = dehydrate(queryClient);


    return (
        <div className="w-[100%] h-[100%]">
            <HydrationBoundary state={dehydratedState}>
                
                {children}
            </HydrationBoundary>
        </div>
    );
}
