import type {Metadata} from "next";
import {ReactNode} from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = { children: ReactNode, receipt:ReactNode}

export default async function MyPageLayout({children,receipt}: Props) {



    return (
        <div className="w-[100%] h-[100%]">
                {receipt}
                {children}
        </div>
    );
}
