import type {Metadata} from "next";
import Header from "./component/Header"
import {ReactNode} from "react";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = { children: ReactNode, modal: ReactNode }

export default async function PostVerificationLayout({children, modal}: Props) {
    return (
        <div className="h-screen">
            <Header/>
            {children}
            {modal}
        </div>
    );
}
