import type {Metadata} from "next";
import "@/styles/globals.css";
import * as styles from '@/styles/app.css'
import {MSWComponent} from "@/app/component/MSWComponent";

export const metadata: Metadata = {
    title: "piepay",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    const getToken = async () => {
        const response = await fetch(`${process.env.NEXT_PUBLIC_FRONTEND_BASE_URL}/api/auth`, {
            method: 'GET'
        })
        const token = await response.json();
        console.log(token);
    }
    getToken();
    return (
        <html lang="en">
            <body className={styles.body} >
            <MSWComponent/>
                <div className={styles.container}>
                    <div className={styles.content}>
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
