import type {Metadata} from "next";
import "@/styles/globals.css";
import * as styles from '@/styles/app.css'
import React from 'react';
import RQProvider from '@/app/(post-verification)/component/RQProvider';

export const metadata: Metadata = {
    title: "piepay",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {

    return (
        <html lang="en">
            <body className={styles.body} >

            <RQProvider>
                <div className={styles.container}>
                    <div className={styles.content}>
                        {children}
                    </div>
                </div>
            </RQProvider>
            </body>
        </html>
    );
}
