import type {Metadata} from "next";
import {ReactNode} from "react";
import {dehydrate, HydrationBoundary, QueryClient} from "@tanstack/react-query";
import {getMembers} from "@/api/member";
import {getMeetInfo, getMeetMembers, getMeetPayments} from "@/api/meet";
import {cookies} from "next/headers";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = {
    children: ReactNode,
    params: { meetId: string },
}

export default async function PaymentModalLayout({children, params}: Props) {
    const token = cookies().get('accessToken');

    const {meetId} = params;
    const queryClient = new QueryClient();
    await queryClient.prefetchQuery({queryKey: ['members', meetId, token?.value], queryFn: getMeetMembers});
    await queryClient.prefetchQuery({queryKey: ['meetInfo', meetId, token?.value], queryFn: getMeetInfo});
    await queryClient.prefetchQuery({queryKey: ['meetPayments', meetId, token?.value], queryFn: getMeetPayments});

    const dehydratedState = dehydrate(queryClient);


    return (
        <>
            <HydrationBoundary state={dehydratedState}>
                {children}
            </HydrationBoundary>
        </>
    );
}
